version: '2'
services:
    restangularjs-app:
        image: restangularjs
        external_links:
            - restangularjs-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/restangularjs
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    restangularjs-postgresql:
        extends:
            file: postgresql.yml
            service: restangularjs-postgresql
